//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allview
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Passport { get; set; }
        public decimal Amount { get; set; }
    }
}
